### ISSUE TITLE
Reflect Manager ownership on the Endpoint contracts

### ISSUE THREAD

**Issue by nik-suri** [wormhole-foundation/example-native-token-transfers#94]
```[tasklist]
### Tasks
- [x] remove OwnableUpgradeable from WormholeEndpointStandalone
- [x] set the owner of the manager and to the owner of the endpoint
- [x] override transferOwnership in ManagerStandalone to loop through all the endpoints and update the owner of all the endpoints to be the owner of the manager
- [x] remove pass through upgrade of endpoints from manager
```
